# Generated by Django 5.0.4 on 2024-04-14 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 14, 5, 44, 40, 44503, tzinfo=datetime.timezone.utc)),
        ),
    ]
