# Generated by Django 5.0.4 on 2024-04-14 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_alter_book_book_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 14, 5, 45, 10, 56942, tzinfo=datetime.timezone.utc)),
        ),
    ]
