# Generated by Django 5.0.4 on 2024-04-19 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_book_book_pic_url_alter_book_book_add_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_pic_url',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 19, 5, 52, 5, 892239, tzinfo=datetime.timezone.utc)),
        ),
    ]
