# Generated by Django 5.0.4 on 2024-04-19 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0005_remove_book_book_pic_url_alter_book_book_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pic_url',
            field=models.CharField(default='https://images.pexels.com/photos/256450/pexels-photo-256450.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 19, 5, 52, 35, 30072, tzinfo=datetime.timezone.utc)),
        ),
    ]
