# Generated by Django 5.0.4 on 2024-04-19 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0006_book_book_pic_url_alter_book_book_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 19, 8, 55, 2, 874936, tzinfo=datetime.timezone.utc)),
        ),
    ]
